### ISSUE TITLE
Aerospace can't be opened even after allowing unverified apps

### ISSUE THREAD

**Issue by pablo-unzueta** [nikitabobko/AeroSpace#165]
Hello! Thank you for the excellent package it was working up until I upgraded my MacOS to Sonoma 14.3.1. I tried installing via homebrew with the given command and it didn't work. I also tried using the manual method, but I'm still getting the warning: The application “AeroSpace.app” can’t be opened.

Any ideas on how to fix

**Comment by nikitabobko** [comment]
I confirm that I saw these two dialogs after Sonoma 14.3.1 update

> The application "AeroSpace.app" can't be opened.

> "AeroSpace.app" will damage your computer. You should move it to the Bin.

<img width="811" alt="Screenshot 2024-02-17 at 01 07 57" src="https://github.com/nikitabobko/AeroSpace/assets/20517828/939fd98c-c05f-4248-949c-599c5fbd1b39">

I just rebuilt the app and published it as a 0.8.5-Beta update. It fixed the problem on my machine

Can you please confirm that it fixes the problem on your machine?

**Comment by pablo-unzueta** [comment]
Fixed! Thanks so much for the prompt response. :)

**Comment by johnallen3d** [comment]
FWIW, and maybe it was just me, I upgraded to AeroSpace `0.8.5-Beta` prior to macOS Sonoma 14.3.1 and started getting this message. After upgrading to 14.3.1 I still received this message on AeroSpace launch. Then I did a `brew uninstall aerospace && brew install aerospace` and all was right in the world again.
